// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package accountgqlclient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// MeMe includes the requested fields of the GraphQL type Me.
type MeMe struct {
	Id string `json:"id"`
}

// GetId returns MeMe.Id, and is useful for accessing the field via an interface.
func (v *MeMe) GetId() string { return v.Id }

// MeResponse is returned by Me on success.
type MeResponse struct {
	Me MeMe `json:"me"`
}

// GetMe returns MeResponse.Me, and is useful for accessing the field via an interface.
func (v *MeResponse) GetMe() MeMe { return v.Me }

func Me(
	ctx context.Context,
	client graphql.Client,
) (*MeResponse, error) {
	req := &graphql.Request{
		OpName: "Me",
		Query: `
query Me {
	me {
		id
	}
}
`,
	}
	var err error

	var data MeResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
