name: CI
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5-focal
        ports:
          - 27017:27017
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: reearth
          POSTGRES_PASSWORD: reearth
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U reearth"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: set up
        uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3
        with:
          go-version: 1.26
      - name: checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: cache
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.11.4
          args: --timeout=10m
      - name: test
        run: go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic -timeout 10m
        env:
          REEARTH_DB: mongodb://localhost
          REEARTH_DB_PG: postgres://reearth:reearth@localhost:5432/postgres?sslmode=disable
      - name: Send coverage report
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.txt
